import os 
import pandas as pd

"""For collating individual point data from output/*verbose.out,
which is generated by running main.py with --save --single_results
"""

# Set the directory path
directory = 'output'

# List all CSV files in the directory
csv_files = [file for file in os.listdir(directory) if file.endswith('_no_project.out')]

# Initialize an empty DataFrame to store the merged data
merged_data = pd.DataFrame()

# Iterate through each CSV file and merge the data
for csv_file in csv_files:
    file_path = os.path.join(directory, csv_file)
    df = pd.read_csv(file_path)
    merged_data = pd.concat([merged_data, df], ignore_index=True)

# Remove all occurrences of the value 1000
merged_data.replace(1000, pd.NA, inplace=True)

# Save the merged and modified data to a new CSV file
merged_data.to_csv('merged_output.csv', index=False)

print('Merged data saved to merged_output.csv')